name: Hello World Workflow

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello ${{ github.actor }}! This is your updated GitHub Actions!"
      
      - name: Print Environment Variables
        run: env
      
      - name: Use Secret Message
        run: echo "The secret message is ${{ secrets.MY_SECRET_MESSAGE }}"
